### ISSUE TITLE
Error when deleting time slots

### ISSUE THREAD

**Issue by rohieb** [kellerben/dudle#78]
I have installed revision acef4a8fe0335b. When I create a new poll, I can choose time slots, but when I then try to delete one by clicking it again, I get a HTTP 502 Bad Gateway in the browser, and the server log shows a stacktrace:
```
/srv/www/dudle/timestring.rb:58:in `<=>': undefined method `date' for nil:NilClass (NoMethodError)
	from /srv/www/dudle/timepollhead.rb:63:in `=='
	from /srv/www/dudle/timepollhead.rb:63:in `!='
	from /srv/www/dudle/timepollhead.rb:63:in `delete_concrete_column'
	from /srv/www/dudle/timepollhead.rb:79:in `delete_column'
	from /srv/www/dudle/poll.rb:473:in `delete_column'
	from /srv/www/dudle//d2n3hwl5/edit_columns.cgi:38:in `<main>'
```

Here is the POST request:
```
POST /d2n3hwl5/edit_columns.cgi HTTP/1.1
Host: dudle.stratum0.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 133
Referer: https://dudle.stratum0.org/d2n3hwl5/edit_columns.cgi
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

The data.yml looks like this:
``` yaml
# This is a dudle poll file
--- !ruby/object:Poll
name: asdf
head: !ruby/object:TimePollHead
  data:
  - !ruby/object:TimeString
    date: 2017-09-29
    time: 2017-09-29 12:00:00.000000000 +02:00
  - !ruby/object:TimeString
    date: 2017-09-29
    time: 2017-09-29 11:00:00.000000000 +02:00
  - !ruby/object:TimeString
    date: 2017-09-29
    time: 2017-09-29 10:00:00.000000000 +02:00
data: {}
comment: []
```
